addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  global:
    # Ignore warnings when running specs.
    - RUBYOPT="-W0"
  matrix:
    - CHEF_VERSION=12.14.89 INSTANCE=default-debian-9
    - CHEF_VERSION=12.14.89 INSTANCE=default-debian-10
    - CHEF_VERSION=12.14.89 INSTANCE=default-ubuntu-1604
    - CHEF_VERSION=12.14.89 INSTANCE=default-ubuntu-1804
    - CHEF_VERSION=12.14.89 INSTANCE=default-centos-6
    - CHEF_VERSION=12.14.89 INSTANCE=default-centos-7
    - CHEF_VERSION=current INSTANCE=default-debian-9
    - CHEF_VERSION=current INSTANCE=default-debian-10
    - CHEF_VERSION=current INSTANCE=default-ubuntu-1604
    - CHEF_VERSION=current INSTANCE=default-ubuntu-1804
    - CHEF_VERSION=current INSTANCE=default-centos-6
    - CHEF_VERSION=current INSTANCE=default-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
